export { default as Footer } from './Footer'
export { default as GithubCorner } from './GithubCorner'
export { default as QuizBackground } from './QuizBackground'
export { default as QuizContainer } from './QuizContainer'
export { default as QuizLogo } from './QuizLogo'
export { default as Widget } from './Widget'
